name: Java CI with Maven and TestNG

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build and Test with Maven
        run: mvn clean test

      - name: Check for Test Failures
        run: |
          if grep -q "<test-method.*status=\"FAIL\"" target/surefire-reports/testng-results.xml; then
            echo "Test failures detected in TestNG XML report."
            exit 1
          fi

      - name: Upload TestNG Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-html-report
          path: target/surefire-reports/emailable-report.html
